python_tests(
    extra_env_vars=[
        "BUILD_ROOT",
    ],
    overrides={
        "test_config.py": {
            "dependencies": ["./data/interpreter-groups.toml"]
         }
    }
)

python_test_utils(
    name="test_utils",
)
