python_sources()

pex_binary(
    name="main",
    entry_point="__main__.py",
    execution_mode="venv",
    output_path="science.pex",
    platforms=[
        "linux_aarch64-cp-310-cp310",
        "linux_x86_64-cp-310-cp310",
        "macosx_10_9_arm64-cp-310-cp310",
        "macosx_10_9_x86_64-cp-310-cp310",
        "win_amd64-cp-310-cp310",
    ]
)