# Copyright 2022 Science project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(
    name="main",
    entry_point="__main__.py",
    execution_mode="venv",
    output_path="science.pex",
)