name: Deploy Doc Site
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Nox
        run: pip install nox
      - name: Checkout Lift
        uses: actions/checkout@v3
      - name: Build Doc Site
        env:
          # N.B.: This makes default paths in generated docs generic.
          XDG_CACHE_HOME: "<USER CACHE DIR>"
        run: nox -e doc
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/build/html/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
