name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to manually run a deploy for.
        required: true
defaults:
  run:
    shell: bash
jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'a-scie' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Noop
        run: "true"
  determine-tag:
    name: Determine the release tag to operate against.
    needs: org-check
    runs-on: ubuntu-22.04
    outputs:
      release-tag: ${{ steps.determine-tag.outputs.release-tag }}
      release-version: ${{ steps.determine-tag.outputs.release-version }}
    steps:
      - name: Determine Tag
        id: determine-tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            RELEASE_TAG=${{ github.event.inputs.tag }}
          else
            RELEASE_TAG=${GITHUB_REF#refs/tags/}
          fi
          if [[ "${RELEASE_TAG}" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "release-tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
            echo "release-version=${RELEASE_TAG#v}" >> $GITHUB_OUTPUT
          else
            echo "::error::Release tag '${RELEASE_TAG}' must match 'v\d+.\d+.\d+'."
            exit 1
          fi
  github-release:
    name: (${{ matrix.name }}) Create Github Release
    needs: determine-tag
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # N.B.: macos-14 is the oldest non-deprecated ARM Mac runner.
        include:
          - os: ubuntu-24.04
            name: Linux x86-64 (musl)
            image: alpine
            arch: amd64
          - os: ubuntu-24.04
            name: Linux x86-64 (glibc)
            image: debian/bookworm
            arch: amd64
          - os: ubuntu-24.04
            name: Linux aarch64
            image: debian/bookworm
            arch: arm64
          - os: ubuntu-24.04
            name: Linux armv7l
            image: debian/bookworm
            arch: arm/v7
          - os: ubuntu-24.04
            name: Linux riscv64
            image: debian/trixie
            arch: riscv64
          - os: ubuntu-24.04
            name: Linux s390x
            image: debian/bookworm
            arch: s390x
          - os: ubuntu-24.04
            name: Linux powerpc64le
            image: debian/bookworm
            arch: ppc64le
          - os: macos-x86_64
            name: macOS x86-64
          - os: macos-14
            name: macOS aarch64
          - os: windows-2022
            name: Windows x86-64
          - os: windows-11-arm
            name: Windows aarch64
    environment: Release
    env:
      FORCE_COLOR: 1
      SCIENCE_AUTH_API_GITHUB_COM_BEARER: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      attestations: write
      contents: write
      discussions: write
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Setup uv
        run: |
          export UV="$(which uv)"
          "${UV}" -V
          echo UV="${UV}" >> ${GITHUB_ENV}
      - name: Setup x86_64 Python for Prism
        if: matrix.os == 'windows-11-arm'
        run: |
          # N.B.: We use an x86-64 Python for Windows ARM64 because this is what we ship with via
          # PBS, and we need to be able to resolve x86-64 compatible requirements (which include
          # native deps like psutil) for our shiv.
          UV_PYTHON_VERSION=cpython-3.13.7-windows-x86_64-none
          "${UV}" python install ${UV_PYTHON_VERSION}
          echo UV_PYTHON_ARGS="--python ${UV_PYTHON_VERSION}" >> ${GITHUB_ENV}
      - name: Installing emulators
        if: matrix.image != ''
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Checkout lift ${{ needs.determine-tag.outputs.release-tag }}
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.determine-tag.outputs.release-tag }}
      - name: Package science ${{ needs.determine-tag.outputs.release-tag }} binary
        if: matrix.image == ''
        run: |
          "${UV}" run ${UV_PYTHON_ARGS} dev-cmd --timings package
      - name: Package science ${{ needs.determine-tag.outputs.release-tag }} binary
        if: matrix.image != ''
        run: |
          "${UV}" run dev-cmd docker -- --image ${{ matrix.image }} --arch ${{ matrix.arch }} \
            --timings package
      - name: Generate science ${{ needs.determine-tag.outputs.release-tag }} artifact attestations
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/science-*
      - name: Prepare Changelog
        id: prepare-changelog
        uses: a-scie/actions/changelog@v1.6
        with:
          changelog-file: ${{ github.workspace }}/CHANGES.md
          version: ${{ needs.determine-tag.outputs.release-version }}
      - name: Create ${{ needs.determine-tag.outputs.release-tag }} Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.determine-tag.outputs.release-tag }}
          name: science ${{ needs.determine-tag.outputs.release-version }}
          body_path: ${{ steps.prepare-changelog.outputs.changelog-file }}
          draft: false
          prerelease: false
          files: dist/science-*
          fail_on_unmatched_files: true
          discussion_category_name: Announcements
      - name: Cleanup
        if: always()
        run: |
          if [[ -n "${CI_BIN_DIR}" && -d "${CI_BIN_DIR}" ]]; then
            rm -rf "${CI_BIN_DIR}"
          fi
